version: '3.7'

networks:
  test:
    name: fabric_test

services:
  ca_bcp:
    image: hyperledger/fabric-ca:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-bcp
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17054
    ports:
      - "7054:7054"
      - "17054:17054"
    command: sh -c 'fabric-ca-server start -b parshant:parshantpw -d'
    volumes:
      - ../bcp.com/certs:/etc/hyperledger/fabric-ca-server/
    container_name: ca_bcp
    networks:
      - test