const messages = {
    register: "User registered successfully ",
    registerError:"Registration unsuccessfull",
    userExists: "User already exists",
    idExists: "unique id is required",
    drugExists: "Drug already Exists",
    unauthorizedEmail: "Invalid email or doesn't exist.",
    UnauthorizedPassword: "Invalid password",
    loginSuccess: "Successful login",
    loginError:"Login unsuccessfull",
    TokenError: "Enter token generated for authorization",
    Changepassword: "Password is updated to new one",
    changepasswordError:"Password not changed",
    UnauthorizedUser: "User doesnot exists anymore",
    updated: "User data updated successfully",
    updationError:"Updation Unsuccessfull",
    mailComposed: "Mail sent ",
    composeError:"Mail composition error",
    messageError: "Message length is more than subscribed plan word limit",
    fileError: "Cannot upload more files than subscribed plan",
    ccError: "cannot add more user in cc than subscribed plan",
    bccError: "cannot add more user in bcc than subscribed plan",
    mssgeIdError: "Invalid mssgeId",
    replyError: "You cannot reply to this mail",
    ErrorReply:"Reply mail error",
    MailReplyed:"You replyed to mail successfully",
    bookmarkError:"You cannot bookmark this mail",
    bookmarked:"mail bookmarked successfully",
    BookmarkError:"mail bookmarking unsuccessfull",
    alreadyBookmarked:"This mail is already bookmarked by you",
    getMailError:"You are not authorized to see this mail",
    mailError:"Unsuccessfull attempt",
    successMail:"You can get the mail",
    deleteMailError:"You are not authorized to delete this mail",
    deleteError:"Mail deletion unsuccessfull",
    successDelete:"Mail successfully deleted",
    alreadyDeleted:"Mail is already deleted by you",
    mssgeDeletedError:"Mail is deleted by you so you cannot perform operation on this mail",
    forwarded:"Mail forwarded successfully",
    forwardError:"You are not authorized to forward this mail",
    forwardMailError:"Mail forward unsuccessfull attempt",
    forwardeduser:"Mails forwarded by you to others",
    forwardTouser:"Mails forwarded by others to me",
    inbox:"Inbox of user",
    inboxError:"Unsuccessfull attempt to get inbox ",
    sent:"sent box of the user",
    senterror:"Unsuccessfull attempt to get sentBox",
    mismatch:"No matching query for data provided by user",
    searcherror:"Search unsuccessfull ",
    search:"Response for search operation :-",
    invalidFields:"Invalid field data",
    missingFields: "one or more field is missing",
    orgNameErr: "invalid entry for organization name",
    streetNoErr: "invalid entry for street name",
    stateNameErr: "invalid entry for state name",
    cityNameErr: "invalid entry for city name",
    pinErr: "invalid entry for pincode",
    phoneErr: "invalid entry for phone number",
    businessRegisterationErr: "invalid entry for business registeration number",
    emailErr: "invalid entry for email",
    passwordErr: "invalid entry for password",
    confirmPassErr: "passwords do not match",
    serverErr: "internal error occured, Please try again after some time",
    drugRegister: "Drug registered successfully",
    idExistsConflict: "userExist in only one database",
    requireLogin: "login required",
    statusError: "you are not allowed to perform this action, contact admin.",
    fetchSuccess: "successfully fetched data",
    profileStatusConflict: "Your profile status is ",
    contactAdmin: " please contact Admin.",
    orderPlaces: "Order Placed successfully.",
    idFound:"id exists",
    idNotFound: "id does not exist"
  };
  
  const responseStatus = {
    success: 1,
    failure: 0,
  };
  
  const statusCode = {
    Ok: 200,
    Created: 201,
    Bad_request: 400,
    Unauthorized: 401,
    Not_Found: 404,
    InternalServerError: 500
  };
  
module.exports = { messages, responseStatus, statusCode };
